FROM postgres:13-alpine

ENV POSTGRES_DB=paqbot
ENV POSTGRES_USER=paqbot_user
ENV POSTGRES_PASSWORD=securepassword

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5400

# Add custom PostgreSQL configuration
COPY postgresql.conf /etc/postgresql/postgresql.conf
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]