FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 5100

ENV PYTHONUNBUFFERED=1
ENV FLASK_APP=engine.py
ENV FLASK_ENV=production

CMD ["python", "engine.py"]